### ISSUE TITLE
get_next_post() and get_previous_post() taxonomy patameters are ignored

### ISSUE THREAD

**Issue by mplusb** [ColorlibHQ/simple-custom-post-order#12]
get_next_post() and get_previous_post() functions work well as long as they’re used without parameters. If taxonomy parameters are provided, for example get_next_post(true, '', 'my-taxonomy') which should query the next post that belongs to the same taxonomy term as the current one, then a result of a function call is the same as if the function was called without any parameter.

So, it seems that there’s something wrong with the get_next_post_where and the get_previous_post_where filter.

**Comment by giucu91** [comment]
Fixed in 2.3.5
