### ISSUE TITLE
move to another page

### ISSUE THREAD

**Issue by beatricelucaci** [ColorlibHQ/simple-custom-post-order#128]
Is there any way to move a post from page 1 to page 3 by dragging and dropping?
If this is not possible, please let me know if there are other ways to move them.

https://wordpress.org/support/topic/how-to-move-to-another-page/

I tested this on my end and I cannot move items from one page to another

**Comment by beatricelucaci** [comment]
+1 https://wordpress.org/support/topic/how-to-sort-when-there-are-multiple-pages/

**Comment by wiegertschouten** [comment]
This can be fixed by opening the Display Options on the right top, and then setting the amount of posts per page to a number that is higher than the total number of posts in the corresponding post type. That way, all posts will be visible and ordering can be done across pages. Closing this.
