### ISSUE TITLE
 Plugin clashing with AJAX requests

### ISSUE THREAD

**Issue by mplusb** [ColorlibHQ/simple-custom-post-order#13]
https://wordpress.org/support/topic/plugin-clashing-with-ajax-requests/

**Comment by razvanaldea89** [comment]
Think this one also has a pull request https://github.com/ColorlibHQ/simple-custom-post-order/pull/44/commits/1fb3ac6b5a3a3d1bc040386e66639af1c5f4a4d4

**Comment by wiegertschouten** [comment]
Closing this as it was fixed a long time ago, see https://github.com/ColorlibHQ/simple-custom-post-order/pull/44
