### ISSUE TITLE
Editor can’t order posts anymore

### ISSUE THREAD

**Issue by beatricelucaci** [ColorlibHQ/simple-custom-post-order#139]
Hi, there is an issue with the latest release of the plugin: Editors are currently unable to save the order of items.

https://wordpress.org/support/topic/editor-cant-order-posts-anymore/

**Comment by beatricelucaci** [comment]
more info from our users: 

it’s line 332 (which is inside the update_menu_order function) that now does a check to see if user can ‘manage_options’. This is really only an administrator capability and should prob be ‘edit_others_posts’ to allow editors to save the menu order. Note that ‘edit_posts’ is probably too wide a capability.

I guess it’s because this is set

current_user_can('manage_options')
So only admin are allowed.
Here in your code: https://plugins.trac.wordpress.org/browser/simple-custom-post-order/tags/2.5.8/simple-custom-post-order.php#L332

In the previous version of 2.5.7 this was not set.

**Comment by wiegertschouten** [comment]
Fixed in version 2.5.9, see https://github.com/ColorlibHQ/simple-custom-post-order/pull/144.
