### ISSUE TITLE
paging – reording items in second page cases incorrect order

### ISSUE THREAD

**Issue by mplusb** [ColorlibHQ/simple-custom-post-order#14]
This is for custom post type custom taxonomy.

I have very many items and I cannot increase page size so that everythign fit into one page.

When I modify oder on second page (for instance, moving element on top) all ordering is broken. This item becomes the number one (even if it is on second page).

**Comment by razvanaldea89** [comment]
Could not recreate the problem. Works well on my side.

**Comment by razvanaldea89** [comment]
Tested again, could not recreate the problem.
