### ISSUE TITLE
Non Admins can’t order posts anymore - remove those line codes

### ISSUE THREAD

**Issue by BenjaminBrodwolf** [ColorlibHQ/simple-custom-post-order#140]
Those lines stop the all other Role except the Admin change the Order:

`if ( ! current_user_can( 'manage_options' ) ) {
			return;
		}` 

Please remove it there:

https://github.com/ColorlibHQ/simple-custom-post-order/blob/5760d45a09385e82b2d324c9e8ad8680b946210e/simple-custom-post-order.php#L332

https://github.com/ColorlibHQ/simple-custom-post-order/blob/5760d45a09385e82b2d324c9e8ad8680b946210e/simple-custom-post-order.php#L385

In the previous version of 2.5.7 this was not set.

Checkout my PR: https://github.com/ColorlibHQ/simple-custom-post-order/pull/141

**Comment by BenjaminBrodwolf** [comment]
https://github.com/ColorlibHQ/simple-custom-post-order/pull/141

**Comment by wiegertschouten** [comment]
Fixed in version 2.5.9, see #144.
