### ISSUE TITLE
_load_textdomain_just_in_time

### ISSUE THREAD

**Issue by beatricelucaci** [ColorlibHQ/simple-custom-post-order#143]
PHP Notice: Function _load_textdomain_just_in_time was called incorrectly. Translation loading for the simple-custom-post-order domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the init action or later. Please see [Debugging in WordPress](https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/) for more information. (This message was added in version 6.7.0.) in /wp-includes/functions.php on line 6114
https://wordpress.org/support/topic/_load_textdomain_just_in_time/

**Comment by chrispink** [comment]
When do we expect a fix for this? It's a PITA.

**Comment by cristianraiber** [comment]
cc @TeoAlex 

merged here but not released: https://github.com/ColorlibHQ/simple-custom-post-order/pull/142 

Please do a w.org release and merge into master

**Comment by beatricelucaci** [comment]
+1

**Comment by wiegertschouten** [comment]
Closing this, since the issue was fixed in 2.5.10 🙂
