### ISSUE TITLE
Sorting issues with custom post types within a custom taxonomy

### ISSUE THREAD

**Issue by cristianraiber** [ColorlibHQ/simple-custom-post-order#24]
https://wordpress.org/support/topic/sorting-issues-with-custom-post-types-within-a-custom-taxonomy/

**Comment by razvanaldea89** [comment]
Could not recreate the problem.

**Comment by razvanaldea89** [comment]
Need a second opinion, but I think this issue can be closed. Couldn't recreate the problem after another test.

**Comment by cristianraiber** [comment]
Will reopen if this issue appears again.
