### ISSUE TITLE
Versione 2.3.6 is broken

### ISSUE THREAD

**Issue by Frykky** [ColorlibHQ/simple-custom-post-order#27]
After upgrade to 2.3.6 my site became all a blank pages.
Renamed folder into simple-custom-post-order_old it start again.
I tried to download new copy of plugin but it's impossibile to activate.

**Comment by Frykky** [comment]
Reinstalled v2.3.4 and everything works fine

**Comment by puikinsh** [comment]
Might be related: https://wordpress.org/support/topic/white-screen-after-upgrade-to-2-3-6/

**Comment by cristianraiber** [comment]
@puikinsh @Frykky - an update has already been released to address this.

**Comment by cristianraiber** [comment]
Related to: #28 

@Frykky - can you please try updating your PHP version to at least 7.2? W.org forum users are reporting this has fixed their issue.
