### ISSUE TITLE
Please follow this

### ISSUE THREAD

**Issue by cristianraiber** [ColorlibHQ/simple-custom-post-order#28]
- https://core.trac.wordpress.org/ticket/43987
- https://core.trac.wordpress.org/ticket/43986
- https://core.trac.wordpress.org/ticket/41191

Once these ^ hit WP Core, issues like the ones we've encountered recently with Simple Custom Post Order ( updates version: 2.3.6/7 ) won't happen again. WordPress already recommends PHP 7.x and above (actually 7.2 and above as of today) and anything lower shouldn't be supported. Heck, PHP 7.1 isn't actively supported since 1st of December, 2018 (only security releases until 1st of December 2019). PHP 7.2 is the _new_ norm.

Some of these tickets were supposed to hit with WP 4.9.9 but alas, we're getting 5.0 without these tickets. Hopefully, 5.1 gets these *much needed* WP/PHP version checks into core. 

This is something that should be followed closely and implemented for all of our plugin network @giucu91.

**Comment by wiegertschouten** [comment]
The tickets mentioned have been merged into WP Core a long time ago, and PHP 7.2 is now the minimum required version for WP, so I don't think this is relevant any more. Closing the issue for the sake of cleanup 🧹
