### ISSUE TITLE
Welcome message doesn't go away

### ISSUE THREAD

**Issue by puikinsh** [ColorlibHQ/simple-custom-post-order#29]
This is the public thread: https://wordpress.org/support/topic/you-made-a-mistake-with-that-terrible-dashboard-nag-panel/

I also received 2 emails so far with the same issue. For me, it works perfectly fine and it goes away once any post type is selected but it doesn't appear to be true for everyone.

**Comment by puikinsh** [comment]
Another report via email:

<img width="1093" alt="screenshot 2018-12-07 12 17 00" src="https://user-images.githubusercontent.com/3451398/49641860-0bde1e80-fa1a-11e8-89e6-624acb2e853d.png">

**Comment by cristianraiber** [comment]
@giucu91 - let's look into this ASAP.

**Comment by giucu91** [comment]
@cristianraiber @puikinsh I have made an update to wp[dot]org now with a fix. I'll wait until our user says it's ok and then I'll close this ticket.

**Comment by cristianraiber** [comment]
Issue's gone.
