### ISSUE TITLE
Database error do_action(admi_init)

### ISSUE THREAD

**Issue by mplusb** [ColorlibHQ/simple-custom-post-order#36]
Query:
UPDATE wp_posts as pt JOIN (
SELECT ID, (@row_number:=@row_number + 1) AS rank
FROM wp_posts
WHERE post_type = ‘product’
AND post_status IN ( ‘publish’, ‘pending’, ‘draft’, ‘private’, ‘future’ )
ORDER BY menu_order ASC ) as pt2
ON pt.id = pt2.id
SET pt.menu_order = pt2.rank;

Caller:
do_action(‘admin_init’)

Component:
Core

Error message:
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ‘rank FROM wp_posts WHERE post_type = ‘prod’ at line 2

Error code:
1064

https://wordpress.org/support/topic/database-error-do_actionadmi_init/

**Comment by razvanaldea89** [comment]
I believe there is a pull request for this one. https://github.com/ColorlibHQ/simple-custom-post-order/pull/37
