### ISSUE TITLE
'menu_order' value wrong after deleting a post. 

### ISSUE THREAD

**Issue by oivinds** [ColorlibHQ/simple-custom-post-order#39]
After deleting a post, and then creating a new post
the first row menu_order value is no longer 1 but 0.
And the second row menu_order is 2.

I experienced this behaviour on both the standard page post type and a custom post type.

Wordpress v 4.9.8. 
Plugins installed:
> Add Featured Image Column
> Better REST API Featured Images
> Custom Post Type UI
> Regenerate Thumbnails
> REST API Toolbox
> Simple Custom Post Order

Thank you for your work with this plugin!

**Comment by oivinds** [comment]
I have checked, by disabling this plugin and deleting all posts under pages, that menu_order begins at 0 and not 1 by default.

This plugin seem to insert menu_order 1 when a new post is created (i.e before pressing save on the new post) when it should be 0.

Btw, it does not matter to me personally if the index starts a 1 instead of 0.  
But, as previously mentioned, when you delete a post, the zero is back.

Maybe all thats missing is to hook into the delete event, i.e trigger a reorder after delete?

**Comment by cristianraiber** [comment]
@razvanaldea89 - look into this when you can, please

**Comment by razvanaldea89** [comment]
Think this one can be closed, tried to make the 0 appear but can't replicate, neither post type pages or custom post type. Below image is after deleting and inserting new custom post.

![simple custom post order](https://user-images.githubusercontent.com/44024114/66393099-5766ad80-e9da-11e9-8542-61c107da7436.PNG)
