### ISSUE TITLE
 SCP is breaking post administration in mobile browser

### ISSUE THREAD

**Issue by laranz** [ColorlibHQ/simple-custom-post-order#4]
If I load WordPress admin on mobile browser and go to Posts listing, I am unable to do anything. If I try to tap on article or to edit/delete/any other link there, it just activate dragndrop function. SCPOrder is just taking over and blocks any attempts to click on any function on article.

Any chance to fix it? May be exception for mobile browsers disabling dragndrop functionality, or some button next to post listing which enables/disables it?

**Comment by cristianraiber** [comment]
@laranz - which/what mobile browser are you using? What resolution?

**Comment by cristianraiber** [comment]
@laranz - can you please reply to this ticket?

**Comment by laranz** [comment]
@cristianraiber I just got it from here: https://wordpress.org/support/topic/scp-is-breaking-mobile-post-administration/ I didn't test it though!

I am currently not with colorlib though.

**Comment by razvanaldea89** [comment]
Can't replicate

**Comment by cristianraiber** [comment]
@razvanaldea89 - please detail your process here. How did you test?

**Comment by razvanaldea89** [comment]
Tested on a wordpress installation ( not localhost ) and editing the custom posts types worked. Maybe different settings than the installation where the bug appeared?

**Comment by razvanaldea89** [comment]
Tested it again and seems to work, can edit/view/trash/quick edit posts.
