### ISSUE TITLE
 Disable sorting on modified main query

### ISSUE THREAD

**Issue by mplusb** [ColorlibHQ/simple-custom-post-order#40]
a way to also exclude the main query if it has been modified with the pre_get_posts action (e. g. the order/orderby parameters have been set explicitly)

**Comment by glebkema** [comment]
+1

I use the `get_posts()` function to compose a list of options for the [custom select field](https://docs.carbonfields.net/#/fields/select) in the admin panel. But the `scporder_pre_get_posts()` method of the `SCPO_Engine` class is called by the `pre_get_posts` hook and redefines the `orderby` and `order` parameters.

The problem disappears after deactivating the plugin or deleting hooks:
```php
remove_all_filters( 'pre_get_posts' );
````
