### ISSUE TITLE
Yoast SEO conflict - breaks table

### ISSUE THREAD

**Issue by mplusb** [ColorlibHQ/simple-custom-post-order#42]
I was experiencing an issue where the table breaks when re-ordering any custom post type or page. I seen a support thread here with the same issue conflicting with ACF plugin which was resolved. Anyway, i tested all plugins and the culprit this time is Yoast SEO Plugin.

**Comment by razvanaldea89** [comment]
Could you describe how you got there and how did you test it? Can't seem to get the same results. Created pages and custom post type and displayed them using `WP_Query` in a page template and seems to work. Also, in the dashboard all looks good, posts / pages are arranged as expected after refresh.

**Comment by razvanaldea89** [comment]
@mplusb

**Comment by mplusb** [comment]
I installed and activated YoastSEO and then tried to reorder my posts. When dragging and dropping a post it breaks the table.
Here is a screenshot: https://gyazo.com/dc1b479e9384c29d7c9f63f3cc6576fc

**Comment by razvanaldea89** [comment]
Fixed

**Comment by razvanaldea89** [comment]
This is fixed now
