### ISSUE TITLE
 Issue with sorting taxonomies

### ISSUE THREAD

**Issue by mplusb** [ColorlibHQ/simple-custom-post-order#49]
https://wordpress.org/support/topic/issue-with-sorting-taxonomies/

**Comment by sermalefico** [comment]
This cause me disapear all taxonomy queries. Roll back to previus version

**Comment by tpaviper** [comment]
This fix also broke things for us as well.
Line 520 ->  $taxonomy = $args['taxonomy'][0]; produces an undefined offset
Needs more testing before release.
