### ISSUE TITLE
Plugin makes post overview tables too tall when there are no posts, 

### ISSUE THREAD

**Issue by mplusb** [ColorlibHQ/simple-custom-post-order#52]
Plugin makes post overview tables too tall when there are no posts, screenshot: https://gyazo.com/16b6e61ec8acd2064dfc429d1fb78d31

**Comment by mplusb** [comment]
and too wide when there are posts. It’s adding an inline “width” style that screws up everything.

**Comment by gavin310** [comment]
I'm having this same problem. It is making my tables too wide, so that I have to scroll horizontally to see the right column.

**Comment by razvanaldea89** [comment]
This should be fixed
