### ISSUE TITLE
 Sort order will not allow drag and drop in admin

### ISSUE THREAD

**Issue by mplusb** [ColorlibHQ/simple-custom-post-order#60]
URL : base_url/wp-admin/edit.php?post_type=press_releases
is working allows drag and drop but When I added sort

URL : base_url/wp-admin/edit.php?post_type=press_releases/orderby=menu_order&order=desc is not allow drag and drop. drag is in active.

I need to set order sort in admin too same as in front so I can manage my nreaking news,

**Comment by wiegertschouten** [comment]
Closing this because it's intended behaviour.
