### ISSUE TITLE
does not work with duplicate page plugin

### ISSUE THREAD

**Issue by mplusb** [ColorlibHQ/simple-custom-post-order#63]
We also have this plugin installed: https://wordpress.org/plugins/duplicate-page/

It looks like: if we duplicate a post with the above plugin, the custom post order is no longer possible for the newly created post. (this duplicate plugin is also on the site for a year now)
When we hit the button ‘update’ under the custom post order settings, all works and we can move all posts around as we want.

As soon as we start adding new posts with the duplicator the problem starts again.

**Comment by TeoAlex** [comment]
The issue seems to be fixed and could not be reproduced.
![image](https://github.com/ColorlibHQ/simple-custom-post-order/assets/19348508/78bda654-d94b-4da3-acfd-83b3851e646e)
