### ISSUE TITLE
 Issue with a custom post type

### ISSUE THREAD

**Issue by mplusb** [ColorlibHQ/simple-custom-post-order#78]
https://wordpress.org/support/topic/issue-with-a-custom-post-type/

I’ve a Divi child theme in which I’ve created a custom post type.
I use your plugin to order these custom types.

I’ve an issue about their order in admin area: when the plugin is active, the custom types are ordered by date ASC rather than DESC.. so I see older custom types instead new one.

**Comment by acupofcode** [comment]
Hi! 
I'm the mentioned post's owner.
I've tried to add this code to my custom type, (with a low priority)
```
function tour_admin_order( $wp_query ) {
  if (is_admin()) {
    $post_type = $wp_query->query['post_type'];
    if ( $post_type == 'tour') {
      $wp_query->set('orderby', 'date');
      $wp_query->set('order', 'DESC');
    }
  }
}
add_filter('pre_get_posts', 'tour_admin_order',1);

```
I think is something can be miss in my code as this issue comes only when plugin is activated.
Many thanks for helping me to understand how to solve.
Anna

**Comment by giucu91** [comment]
Hello @acupofcode, use this : 
```
function tour_admin_order( $wp_query ) {
  if (is_admin()) {
    $post_type = $wp_query->query['post_type'];
    if ( $post_type == 'tour') {
      $wp_query->set('orderby', 'date');
      $wp_query->set('order', 'DESC');
    }
  }
}
add_filter('pre_get_posts', 'tour_admin_order',99);
```

**Comment by acupofcode** [comment]
Thank but it doesn't work.
If active this action, order of custom type isnt' like front end and I cannot adjust.
I waited to reply to you because I've done several tests.
Anna
