### ISSUE TITLE
 Plugin generates PHP Warning

### ISSUE THREAD

**Issue by mplusb** [ColorlibHQ/simple-custom-post-order#8]
The plugin now creates the following error when WP_DEBUG is turned on:

Notice: get_screen_icon is <strong>deprecated</strong> since version 3.8.0 with no alternative available. in C:\wamp64\www\client\greenchameleon\wp-includes\functions.php on line 3856

This error appears on admin.php?page=scporder-settings

**Comment by cristianraiber** [comment]
Fixed in: https://github.com/ColorlibHQ/simple-custom-post-order/pull/20
