### ISSUE TITLE
 Post order conflicts with WP ‘Recent Posts’ widget

### ISSUE THREAD

**Issue by mplusb** [ColorlibHQ/simple-custom-post-order#81]
After changing the order of certain posts on a page, my ‘recent posts’ widget (built-in WP widget) changes the order as well even though it is set to show recent posts by date.

https://wordpress.org/support/topic/post-order-conflicts-with-wp-recent-posts-widget/

**Comment by TeoAlex** [comment]
![image](https://github.com/ColorlibHQ/simple-custom-post-order/assets/19348508/f854f42f-7fb2-4be6-98f4-8125554f0090)
![image](https://github.com/ColorlibHQ/simple-custom-post-order/assets/19348508/637c29a7-7f95-4562-9ae5-0a8d62256c8d)

Works now.
