### ISSUE TITLE
Ordering terms by e.g. name should be possible when using this plugin.

### ISSUE THREAD

**Issue by fkallevik** [ColorlibHQ/simple-custom-post-order#85]
Currently I have not found a way to get terms from a taxonomy ordered by e.g. `name`. I have tried setting the `orderby` arg, but it seems this plugin just forces the `orderby` to be the custom post order set by the plugin.

It's fine that this is the default order when the plugin is active, but it really should be possible to override using either `suppress_filters` or just by setting the `orderby` arg explicitly in the `get_terms` arguments.

Hope this feature can be considered as I really appreciate this plugin, but this feature is needed for it to be 🔥

Thanks!

**Comment by TeoAlex** [comment]
Just tested and `suppress_filters` works.
 ex: `$terms = get_terms( [ 'taxonomy' => 'project_category', 'hide_empty' => false, 'orderby'  => 'slug', 'suppress_filter' => 'true' ] );`
