### ISSUE TITLE
0 side padding causes item collision

### ISSUE THREAD

**Issue by ribeiroeder** [ColorlibHQ/simple-custom-post-order#86]
The lines 
$(this).css('padding','8px 0px');

in file scporder.js removes side spacing of columns, causing collision between items.

I've done simulations removing these CSS padding assignments and the columns are back to normal (as if I had disabled the plugin)

![mobile](https://user-images.githubusercontent.com/24439523/85191955-23e16000-b297-11ea-8983-88a02a559691.jpg)

![desktop](https://user-images.githubusercontent.com/24439523/85191958-2774e700-b297-11ea-9688-6bcf0efaee51.jpg)

**Comment by ribeiroeder** [comment]
With the plugin disabled, the items return to respect the spacing.

![plugin-off](https://user-images.githubusercontent.com/24439523/85192072-93efe600-b297-11ea-96ea-ee5ee02e2343.jpg)

**Comment by webaxones** [comment]
Same here : the fix code named "Fix for table breaking" break admin table. Post title seems to take up all the space and the other columns are kept to a minimum.
