### ISSUE TITLE
order duplicate titles

### ISSUE THREAD

**Issue by mplusb** [ColorlibHQ/simple-custom-post-order#9]
We’re using this to control the order of Staff litings – each staff member person is a custom post type with their surname as the title of the post.

The plugin is working well EXCEPT – we have both an Andy Davis and Dana Davis. We need Dana to be listed first, but when we switch them on the backend, they always display with Andy first.

The posts have different slugs (‘a-davis’ and ‘d-davis’) and if we move Dana further up the list, she is ordered correctly.

**Comment by razvanaldea89** [comment]
Can't replicate. Tried multiple custom post types with multiple variations. The final order is exactly the order set.

**Comment by razvanaldea89** [comment]
Tested again, can't replicate this issue. Seems to work fine
