### ISSUE TITLE
WordPress 5.5 Issue

### ISSUE THREAD

**Issue by DuckDivers** [ColorlibHQ/simple-custom-post-order#94]
https://github.com/ColorlibHQ/simple-custom-post-order/blob/c90fc19ef8855f22d52814c2561b687a2bd6d909/assets/scporder.js#L34

This needs to be changed to

`jQuery(window).on('load', function () {`

Thank you.

**Comment by cristianraiber** [comment]
cc @andyluak

**Comment by DuckDivers** [comment]
Thank you... This plugin is great by the way...
