### ISSUE TITLE
Allow custom orderby in Gutenberg block preview

### ISSUE THREAD

**Issue by christophrado** [ColorlibHQ/simple-custom-post-order#98]
We're using SCPO alongside custom blocks that allow setting a custom order of objects.
SCPO overwrites the orderby parameter in queries within blocks in the editor preview/admin.

I narrowed the issue down to line 498, where the check says
`if (isset($wp_query->query['post_type']) && !isset($_GET['orderby'])) {`
Changing this to
`if (isset($wp_query->query['post_type']) && !isset($wp_query->query['orderby'])) {`
allows for queries with custom orderby values within the editor.

I've not found any issues with rewriting this line. Orders set by SCPO still work in other admin screens. This might need more testing though. If this isn't conflicting with other screens, I'd welcome this change for better block compatibility.

**Comment by giucu91** [comment]
fixed in 2.5.5
