### ISSUE TITLE
WP 5.5 compatibility update

### ISSUE THREAD

**Issue by ViSi19** [ColorlibHQ/simple-custom-post-order#99]
https://wordpress.org/support/topic/jquery-deprecation/

**Comment by janisii** [comment]
Temp fix for jQuery.fn.load() is deprecated error.

File: simple-custom-post-order/assets/scporder.js and line 34:     

change:
`jQuery(window).load(function () { `

to:
`jQuery(window).on("load", function () {`

**Comment by DuckDivers** [comment]
This is still throwing notices about the `.load` function on line 34.
